# Generated by Django 5.2.7 on 2025-10-21 17:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_position', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=600)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('company_name', models.CharField(max_length=255)),
                ('city_location', models.CharField(blank=True, max_length=255, null=True)),
                ('vacancy', models.PositiveIntegerField(default=1)),
                ('job_nature', models.CharField(blank=True, choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Remote', 'Remote'), ('Freelance', 'Freelance')], max_length=20, null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('company_description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('skills', models.TextField(blank=True, help_text='Comma-seperated list of skills', null=True)),
                ('experience', models.TextField(blank=True, help_text='Comma-seperated list of skills', null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='Dashboard.category')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cv', models.FileField(upload_to='cvs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='Dashboard.job')),
            ],
            options={
                'unique_together': {('job', 'applicant')},
            },
        ),
    ]
