# Generated by Django 5.2.7 on 2025-10-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_alter_job_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_filled',
            field=models.BooleanField(default=False),
        ),
    ]
