# Generated by Django 5.2.7 on 2025-10-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_job_category_job_job_type_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='city_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='company_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='job_images/'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_nature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='skills_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='vacancy',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='yearly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
