# Generated by Django 5.2.7 on 2025-10-16 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_job_application_deadline_job_city_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='yearly_salary',
        ),
    ]
