# Generated by Django 5.2.7 on 2025-10-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_remove_job_yearly_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='experience_list',
        ),
        migrations.RemoveField(
            model_name='job',
            name='skills_list',
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.TextField(blank=True, help_text='Comma-seperated list of skills', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-seperated list of skills', null=True),
        ),
    ]
