# Generated by Django 5.2.7 on 2025-10-16 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_remove_job_experience_list_remove_job_skills_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_type',
        ),
    ]
