# Generated by Django 5.2.7 on 2025-10-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0008_alter_job_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
