# Generated by Django 5.2.7 on 2025-10-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0009_alter_job_experience_alter_job_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.TextField(blank=True, help_text='Comma-seperated list of skills', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-seperated list of skills', null=True),
        ),
    ]
