# Generated by Django 5.2.7 on 2025-10-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0011_remove_job_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_nature',
            field=models.CharField(blank=True, choices=[('Full-time', 'Full-Time'), ('Part-time', 'Part-Time'), ('Freelance', 'Freelance'), ('Remote', 'Remote'), ('Internship', 'Internship')], max_length=20, null=True),
        ),
    ]
