# Generated by Django 5.2.7 on 2025-10-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0012_alter_job_job_nature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_nature',
            field=models.CharField(blank=True, choices=[('Full time', 'Full Time'), ('Part time', 'Part Time'), ('Freelance', 'Freelance')], max_length=20, null=True),
        ),
    ]
